In [ ]:
# Numpy array IV

In [3]:
import numpy as np

In [4]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [6]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr[0][0]

5

In [7]:
arr[1] # fila 1

array([20, 25, 30])

In [8]:
arr[1][1] # fila y columna

25

In [9]:
arr[1,1] # fila x columna

25

In [13]:
arr[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [18]:
arr = np.arange(0,11)

In [19]:
bool_arr = arr > 5 

In [20]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [21]:
# ¿Cuales son los valores true?

arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [23]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [25]:
arr_m = np.arange(50).reshape(5,10)

In [26]:
arr_m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
arr_m[1:3,1:3]

array([[11, 12],
       [21, 22]])