In [ ]:
# Numpy array II

In [3]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8] # posicion 8

8

In [8]:
arr[1:5] # parte de un array

array([1, 2, 3, 4])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
# cambiar valor

arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_slice = arr[0:3].copy()

In [23]:
arr_slice

array([0, 1, 2])

In [24]:
arr_slice[:] = 10

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_slice

array([10, 10, 10])