In [ ]:
# Numpy array Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr * arr # multiplicamos por él mismo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr * 2 # multiplicamos por 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr ** 2 # elevamos al cuadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
np.sqrt(arr) # raiz cuadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
np.exp(arr) # exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.cos(arr) # coseno

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [15]:
np.max(arr) # máximo

10

In [16]:
np.min(arr) # mínimo

0