In [1]:
# Numpy Arrays I

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Funciones de ayuda

# help(np.arange)
# np.arange?

In [8]:
# Creamos un array que comienza en 0 e irá espaciado en 2 hasta el 11 (sin incluir)

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# Creamos un array que comemienza en 0 e irá espaciado en 3 hasta el 11 (sin incluir)

np.arange(0,11,3)

array([0, 3, 6, 9])

In [10]:
# Creamos un array de ceros con 7 posiciones

np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Creamos una matriz 5x5 de ceros
# fila x columna

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# Creamos una matriz de 2x3 de ceros
# fila x columna

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Creamos un array de unos

np.ones(3)

array([1., 1., 1.])

In [14]:
# Creamos una matriz 2x8 de unos

np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
# Array con 10 elementos que termina con el valor 5 y empieza con el 0

np.linspace(start = 0, stop = 5, num = 10) 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
# Matriz identidad

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Generamos una matriz de números aleatorios
# np.random.rand?

np.random.rand(5,5)

array([[2.06427113e-01, 5.60211236e-01, 2.63285333e-01, 9.52108602e-01,
        9.59331753e-01],
       [9.01021673e-01, 4.52181987e-01, 3.52062360e-04, 9.81429299e-01,
        2.57835046e-01],
       [5.80142232e-01, 4.82001973e-01, 8.51320570e-01, 2.11912115e-01,
        4.29625019e-01],
       [9.41649492e-01, 5.45121856e-01, 8.81266312e-01, 6.50127924e-01,
        8.78399854e-01],
       [8.31353087e-02, 9.88738626e-01, 4.23729522e-01, 9.97392458e-01,
        8.78057041e-01]])

In [18]:
np.random.rand(6)

array([0.02111251, 0.54538347, 0.77427606, 0.29595187, 0.84067619,
       0.56834699])

In [19]:
# Generamos una matriz de números aleatorios que siguen la distribución normal(0,1) standar
# np.random.randn?

np.random.randn(5,5)

array([[ 1.46807435,  0.61452796,  0.16142293, -0.42970161,  0.25981583],
       [ 0.69328935, -0.734384  ,  0.06856689,  1.82029323, -1.01323317],
       [-1.18025674,  1.14647294,  1.10756578,  0.08358552, -0.83361678],
       [-0.12098484, -0.55066552,  0.44709186, -0.80311616, -0.25639978],
       [ 0.22900676, -2.34403726,  0.78883539, -1.29518915, -0.87853603]])

In [20]:
np.random.randn(8)

array([ 0.92392939,  0.15915471, -0.00519013, -1.3397716 ,  1.46387105,
        1.87140424,  0.43353473, -0.27312442])

In [21]:
# Creamos un array de 10 (size) números aleatorios enteros
# El valor low se incluye y el high no.

# np.random.randint?

np.random.randint(low = 1, high = 100, size = 10)

array([89, 50, 12, 37, 75, 93, 89, 66,  6, 94])

In [22]:
# Ejemplo.
# Con las funciones que hemos realizado, crear un array del 0 al 25

arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
# Otra forma equivalente con la funcion randint

rearr = np.random.randint(0,50,10)

In [37]:
rearr

array([34, 33,  6,  5, 34, 30, 41, 21,  4, 17])

In [26]:
# Reshape en una matriz

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
# Funciones que se pueden aplicar a los arrays
# máximo valor del array
max(rearr)

48

In [28]:
# máximo valor del array (otro método)
rearr.max()

48

In [29]:
# mínimo valor del array
rearr.min()

1

In [30]:
# Posición en la que se encuentra en máximo valor
rearr.argmax()

4

In [31]:
rearr

array([ 9, 47, 29, 19, 48, 47, 44,  1, 31, 37])

In [32]:
# Posición en la que se encuentra en mínimo valor
rearr.argmin()

7

In [33]:
rearr

array([ 9, 47, 29, 19, 48, 47, 44,  1, 31, 37])

In [38]:
# media valor del array
rearr.mean()

22.5

In [42]:
# media valor del array
np.median(rearr)

25.5

In [34]:
# Dimensión del vector

rearr.shape

(10,)

In [35]:
# Redimensionamos el vector

rearr = rearr.reshape(5,2)

In [105]:
rearr

array([[10, 44],
       [47, 19],
       [ 6, 19],
       [35, 22],
       [49, 27]])

In [106]:
# Tipo de datos que contiene el array

rearr.dtype

dtype('int32')